service: 'embrasure'

provider:
    name: aws
    runtime: nodejs18.x
    stage: dev
    region: us-east-1

functions:
    app:
        handler: src/api/index.handler
        events:
            - http:
                  path: /secret
                  method: GET
            - http:
                  path: /secret
                  method: DELETE
            - http:
                  path: /secret
                  method: PATCH
            - http:
                  path: /secrets
                  method: GET
            - http:
                  path: /secrets
                  method: POST
            - http:
                  path: /users
                  method: POST
