service: 'embrasure'
useDotenv: true

provider:
    name: aws
    runtime: nodejs18.x
    stage: v1
    region: us-east-1
    iam:
        role:
            statements:
                - Effect: Allow
                  Action: '*'
                  Resource: '*'

functions:
    app:
        handler: src/index.handler

        events:
            - http:
                  path: /secrets/{key}
                  method: GET
            - http:
                  path: /secrets/{key}
                  method: DELETE
            - http:
                  path: /secrets
                  method: GET
            - http:
                  path: /secrets
                  method: POST
            - http:
                  path: /secrets/{key}
                  method: PATCH
            - http:
                  path: /users
                  method: GET
            - http:
                  path: /users
                  method: POST
            - http:
                  path: /users/{username}
                  method: DELETE
            - http:
                  path: /users/{username}
                  method: GET
            - http:
                  path: /users/{username}
                  method: PUT
