service: 'embrasure'
useDotenv: true

provider:
    name: aws
    runtime: nodejs18.x
    stage: v1
    region: ${env:AWS_REGION} # Replace with your team

functions:
    app:
        handler: src/index.handler
        environment:
            LOGS_WORKER_ACCESS_KEY: ${env:LOGS_WORKER_ACCESS_KEY}
            LOGS_WORKER_SECRET_ACCESS_KEY: ${env:LOGS_WORKER_SECRET_ACCESS_KEY}
        vpc:
            securityGroupIds:
                - ${env:SECURITY_GROUP_ID} # Replace with your security group ID
            subnetIds:
                - ${env:SUBNET_0_ID} # Replace with your subnet ID
                - ${env:SUBNET_1_ID} # Add more subnet IDs if needed
        events:
            - http:
                  path: /secrets/{key}
                  method: GET
            - http:
                  path: /secrets/{key}
                  method: DELETE
            - http:
                  path: /secrets
                  method: GET
            - http:
                  path: /secrets
                  method: POST
            - http:
                  path: /secrets/{key}
                  method: PATCH
            - http:
                  path: /users
                  method: GET
            - http:
                  path: /users
                  method: POST
            - http:
                  path: /users/{username}
                  method: DELETE
            - http:
                  path: /users/{username}
                  method: GET
            - http:
                  path: /users/{username}
                  method: PUT
            - http:
                  path: /logs
                  method: GET
